image: Visual Studio 2017

init:
- git config --global core.autocrlf true

environment:
  DOTNET_VERSION: 3.0.100-preview3-010431

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: $installScript = [System.IO.Path]::Combine([System.IO.Path]::GetTempPath(), [System.IO.Path]::GetRandomFileName())
  - ps: Invoke-WebRequest "https://dot.net/v1/dotnet-install.ps1" -OutFile $installScript -UseBasicParsing
  - ps: '& $installScript -Version "$env:DOTNET_VERSION" -InstallDir "$env:DOTNET_INSTALL_DIR" -NoPath'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
- ps: ci\build.ps1 

test_script:
- ps: ci\test.ps1

artifacts:
- path: artifacts\*.nupkg

deploy:
- provider: NuGet
  server: https://www.myget.org/F/domaindrivendev/api/v2
  on:
    branch: master
    appveyor_repo_tag: false
  api_key:
    secure: 9QrW8KWCDr8G2ufmOX4O7U4yjneFOYY+5h+auICuWYb1YPaKpQBtUVqrRExg8VXR
  skip_symbols: true

- provider: NuGet
  server: https://www.nuget.org/api/v2/package
  on:
    branch: master
    appveyor_repo_tag: true
  api_key:
    secure: S2MgK7qypxpy/OtArorFwdH1XASpkxeJu4L7JtgiEBVWe9bOUQ0D8huWmf4VGrBZ
  skip_symbols: true
